version: '3.8'
services:
  oracle-db:
    image: oracle/database:19.3.0-ee-slim-faststart
    environment:
      - ORACLE_PASSWORD=12345
      - ORACLE_SID=ORCLCDB
      - APP_USER=nyakamwe
      - APP_USER_PASSWORD=12345
      - ORACLE_PDB=ORCLPDB1
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/12345@/localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
  oracle-backup:
